screen_name: "YOUR_SCREEN_NAME"
consumer_key: "YOUR_CONSUMER_KEY"
consumer_secret: "YOUR_CONSUMER_SECRET"
access_token: "YOUR_ACCESS_TOKEN"
access_token_secret: "YOUR_ACCESS_TOKEN_SECRET"
reply_pattern_yaml: "reply_pattern.yaml"
random_pattern_yaml: "random_pattern.yaml"
last_tweet_yaml: "lasttweet.yaml"

